### ISSUE TITLE
[Unidentified bug] Minetest freezes without any errors

### ISSUE THREAD

**Issue by ClobberXD** [ClobberXD/aluminum#1]
If a world is loaded with aluminium enabled, the game freezes when the progress bar label says `Creating server...`, and the issue persists even after fixing a [few minor issues](https://github.com/ClobberXD/aluminium/commits/master), so they're unrelated. No errors are displayed, nothing weird in [debug.txt](https://gist.github.com/ClobberXD/ef8fc5e4b94c8cc8f04fdfaa42890813)

I'd like testers to try it out if possible, maybe also review the code, and provide feedback.

Thanks

**Comment by rubenwardy** [comment]
https://github.com/ClobberXD/aluminium/commit/083bdcbfd7bb56499f563c7627441d4649e088bc#commitcomment-28530393

**Comment by skittlemittle** [comment]
I noticed that crafting an aluminium block from ingots only yields one aluminium block.
 Is this intended?

**Comment by ClobberXD** [comment]
@afshaan4 yes it is - just like steel, tin, copper or bronze blocks

**Comment by ClobberXD** [comment]
Fixed, thanks to @afshaan4 and @rubenwardy
